version: '3.5'

services:

  jenkins-slave:
    image: mborne/jenkins-slave
    build: .
    environment:
      - "JENKINS_USERNAME=${JENKINS_USERNAME}"
      - "JENKINS_PASSWORD=${JENKINS_PASSWORD}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    restart: unless-stopped

networks:
  default:
    external:
      name: devbox
